FROM maven:3.9.2-openjdk-17 AS builder

WORKDIR /app

COPY pom.xml .

RUN mvn dependency:go-offline

COPY src ./src

RUN mvn package

FROM openjdk:17-slim AS final

WORKDIR /app

COPY --from=builder /app/target/your-application.jar .